from easydict import EasyDict

import os
DATA_ROOT = os.environ.get("GRAIL_DATA_ROOT", os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "cyberdata"))

def parameter_parser(dataset="otc", pred_snap='single', attack=True,
                     atype='bad_mouthing', victim_percentage=0.1,
                     homogeneous_edges=True, model='s3r',
                     epochs=50, lambda_temp=0.01):

    base = {
        "single_prediction": pred_snap == 'single',
        "time_slots": 10,
        "train_time_slots": 2,
        "seed": 42,
        "layers": [32, 64, 32],
        "learning_rate": 0.005,
        "weight_decay": 1e-5,
        "epochs": epochs,
        "dropout": 0.0,
        "attack": attack,
        "attack_type": atype,
        "attack_percentage": 1.0,
        "attack_target_future": True,
        "enable_task3": False,
        "victim_percentage": victim_percentage,
        "homogeneous_edges": homogeneous_edges,
        "model": model,
        "lambda_temp": lambda_temp,
        "adv_flip_ratio": 0.02,
        "robust_aggr": False,
    }

    if dataset.lower() in ["otc", "bitcoinotc"]:
        dataset_args = {
            "dataset": "BitcoinOTC",
            "edge_path": os.path.join(DATA_ROOT, "bitcoinotc-rating.txt"),
            "data_path": os.path.join(DATA_ROOT, "bitcoinotc.csv"),
            "attention_head": 16,
            "attention_dropout": 0.3,
        }
    elif dataset.lower() in ["epinions", "epinion", "epn"]:
        dataset_args = {
            "dataset": "Epinions",
            "edge_path": os.path.join(DATA_ROOT, "epinions-rating.txt"),
            "data_path": os.path.join(DATA_ROOT, "epinions.csv"),
            "num_nodes": 131828,
            "attention_head": 8,
            "attention_dropout": 0.2,
        }
    elif dataset.lower() in ["alpha", "bitcoinalpha"]:
        dataset_args = {
            "dataset": "BitcoinAlpha",
            "edge_path": os.path.join(DATA_ROOT, "bitcoinalpha-rating.txt"),
            "data_path": os.path.join(DATA_ROOT, "bitcoinalpha.csv"),
            "attention_head": 16,
            "attention_dropout": 0.2,
        }
    elif dataset.lower().startswith("epn") and dataset.lower()[3:].isdigit():
        # Subsampled Epinions variant (e.g. 'epn30000') for the E10 scaling curve;
        # files generated by run_e10_scaling.make_epn_subsample. num_nodes is inferred
        # from the (renumbered, contiguous) data like otc/alpha.
        n = dataset.lower()[3:]
        dataset_args = {
            "dataset": f"Epinions{n}",
            "edge_path": os.path.join(DATA_ROOT, f"epn{n}-rating.txt"),
            "data_path": os.path.join(DATA_ROOT, f"epn{n}.csv"),
            "attention_head": 8,
            "attention_dropout": 0.2,
        }
    elif dataset.lower().startswith("edt") and dataset.lower()[3:].isdigit():
        # Dated Epinions subgraph (e.g. 'edt30000'): Massa & Avesani's Extended Epinions,
        # the SNAP statements with their real creation dates; files generated by
        # code/make_epinions_dated.py. Same hyperparameters as epn<N>.
        n = dataset.lower()[3:]
        dataset_args = {
            "dataset": f"EpinionsDated{n}",
            "edge_path": os.path.join(DATA_ROOT, f"edt{n}-rating.txt"),
            "data_path": os.path.join(DATA_ROOT, f"edt{n}.csv"),
            "attention_head": 8,
            "attention_dropout": 0.2,
        }
    elif dataset.lower().startswith("edg") and dataset.lower()[3:].isdigit():
        # Dated Epinions, genuine creation dates only: edt<N> without the 578,996 statements
        # stamped with the placeholder first date (code/make_epinions_dated.py --genuine-dates).
        n = dataset.lower()[3:]
        dataset_args = {
            "dataset": f"EpinionsGenuineDates{n}",
            "edge_path": os.path.join(DATA_ROOT, f"edg{n}-rating.txt"),
            "data_path": os.path.join(DATA_ROOT, f"edg{n}.csv"),
            "attention_head": 8,
            "attention_dropout": 0.2,
        }
    else:
        raise ValueError(f"Unknown dataset: {dataset}. Choose 'otc', 'epn', 'alpha', 'epn<N>', 'edt<N>', or 'edg<N>'.")

    base.update(dataset_args)
    return EasyDict(base)
